function sportFunction() {
  document.getElementById("sportOne").style.display = "inline-block";
  document.getElementById("sportTwo").style.display = "inline-block";
  document.getElementById("mySuv-1").style.display = "none";
  document.getElementById("mySuv-2").style.display = "none";
  document.getElementById("mySuv-3").style.display = "none";
  document.getElementById("mySuv-4").style.display = "none";
  document.getElementById("mySuv-5").style.display = "none";
  document.getElementById("mySuv-6").style.display = "none";
  document.getElementById("mySedan").style.display = "none";
  document.getElementById("myHatchback-1").style.display = "none";
  document.getElementById("myHatchback-2").style.display = "none";
  document.getElementById("myContainer").style.height = "fit-content";
  document.getElementById("noContent").style.display = "none";
  document.getElementById("filterContainer").style.borderBottomRightRadius = "10px";
}
function suvFunction() {
  document.getElementById("sportOne").style.display = "none";
  document.getElementById("sportTwo").style.display = "none";
  document.getElementById("mySuv-1").style.display = "inline-block";
  document.getElementById("mySuv-2").style.display = "inline-block";
  document.getElementById("mySuv-3").style.display = "inline-block";
  document.getElementById("mySuv-4").style.display = "inline-block";
  document.getElementById("mySuv-5").style.display = "inline-block";
  document.getElementById("mySuv-6").style.display = "inline-block";
  document.getElementById("mySedan").style.display = "none";
  document.getElementById("myHatchback-1").style.display = "none";
  document.getElementById("myHatchback-2").style.display = "none";
  document.getElementById("myContainer").style.height = "fit-content";
  document.getElementById("noContent").style.display = "none";
    document.getElementById("filterContainer").style.borderBottomRightRadius = "10px";
}
function mpvFunction() {
  document.getElementById("sportOne").style.display = "none";
  document.getElementById("sportTwo").style.display = "none";
  document.getElementById("mySuv-1").style.display = "none";
  document.getElementById("mySuv-2").style.display = "none";
  document.getElementById("mySuv-3").style.display = "none";
  document.getElementById("mySuv-4").style.display = "none";
  document.getElementById("mySuv-5").style.display = "none";
  document.getElementById("mySuv-6").style.display = "none";
  document.getElementById("mySedan").style.display = "none";
  document.getElementById("myHatchback-1").style.display = "none";
  document.getElementById("myHatchback-2").style.display = "none";
  document.getElementById("myContainer").style.height = "fit-content";
  document.getElementById("noContent").style.display = "grid";
    document.getElementById("filterContainer").style.borderBottomRightRadius = "10px";
}
function sedanFunction() {
  document.getElementById("sportOne").style.display = "none";
  document.getElementById("sportTwo").style.display = "none";
  document.getElementById("mySuv-1").style.display = "none";
  document.getElementById("mySuv-2").style.display = "none";
  document.getElementById("mySuv-3").style.display = "none";
  document.getElementById("mySuv-4").style.display = "none";
  document.getElementById("mySuv-5").style.display = "none";
  document.getElementById("mySuv-6").style.display = "none";
  document.getElementById("mySedan").style.display = "inline-block";
  document.getElementById("myHatchback-1").style.display = "none";
  document.getElementById("myHatchback-2").style.display = "none";
  document.getElementById("myContainer").style.height = "fit-content";
  document.getElementById("noContent").style.display = "none";
    document.getElementById("filterContainer").style.borderBottomRightRadius = "10px";
}
function coupeFunction() {
  document.getElementById("sportOne").style.display = "none";
  document.getElementById("sportTwo").style.display = "none";
  document.getElementById("mySuv-1").style.display = "none";
  document.getElementById("mySuv-2").style.display = "none";
  document.getElementById("mySuv-3").style.display = "none";
  document.getElementById("mySuv-4").style.display = "none";
  document.getElementById("mySuv-5").style.display = "none";
  document.getElementById("mySuv-6").style.display = "none";
  document.getElementById("mySedan").style.display = "none";
  document.getElementById("myHatchback-1").style.display = "none";
  document.getElementById("myHatchback-2").style.display = "none";
  document.getElementById("myContainer").style.height = "fit-content";
  document.getElementById("noContent").style.display = "grid";
    document.getElementById("filterContainer").style.borderBottomRightRadius = "10px";
}
function hatchbackFunction() {
  document.getElementById("sportOne").style.display = "none";
  document.getElementById("sportTwo").style.display = "none";
  document.getElementById("mySuv-1").style.display = "none";
  document.getElementById("mySuv-2").style.display = "none";
  document.getElementById("mySuv-3").style.display = "none";
  document.getElementById("mySuv-4").style.display = "none";
  document.getElementById("mySuv-5").style.display = "none";
  document.getElementById("mySuv-6").style.display = "none";
  document.getElementById("mySedan").style.display = "none";
  document.getElementById("myHatchback-1").style.display = "inline-block";
  document.getElementById("myHatchback-2").style.display = "inline-block";
  document.getElementById("myContainer").style.height = "fit-content";
  document.getElementById("noContent").style.display = "none";
    document.getElementById("filterContainer").style.borderBottomRightRadius = "10px";
}
function twoFunction() {
  document.getElementById("sportOne").style.display = "inline-block";
  document.getElementById("sportTwo").style.display = "inline-block";
  document.getElementById("mySuv-1").style.display = "none";
  document.getElementById("mySuv-2").style.display = "none";
  document.getElementById("mySuv-3").style.display = "none";
  document.getElementById("mySuv-4").style.display = "none";
  document.getElementById("mySuv-5").style.display = "none";
  document.getElementById("mySuv-6").style.display = "none";
  document.getElementById("mySedan").style.display = "none";
  document.getElementById("myHatchback-1").style.display = "none";
  document.getElementById("myHatchback-2").style.display = "none";
  document.getElementById("myContainer").style.height = "fit-content";
  document.getElementById("noContent").style.display = "none";
    document.getElementById("filterContainer").style.borderBottomRightRadius = "10px";
}
function fourFunction() {
  document.getElementById("sportOne").style.display = "none";
  document.getElementById("sportTwo").style.display = "none";
  document.getElementById("mySuv-1").style.display = "none";
  document.getElementById("mySuv-2").style.display = "none";
  document.getElementById("mySuv-3").style.display = "none";
  document.getElementById("mySuv-4").style.display = "none";
  document.getElementById("mySuv-5").style.display = "none";
  document.getElementById("mySuv-6").style.display = "none";
  document.getElementById("mySedan").style.display = "none";
  document.getElementById("myHatchback-1").style.display = "inline-block";
  document.getElementById("myHatchback-2").style.display = "inline-block";
  document.getElementById("myContainer").style.height = "fit-content";
  document.getElementById("noContent").style.display = "none";
    document.getElementById("filterContainer").style.borderBottomRightRadius = "10px";
}
function sixFunction() {
  document.getElementById("sportOne").style.display = "none";
  document.getElementById("sportTwo").style.display = "none";
  document.getElementById("mySuv-1").style.display = "inline-block";
  document.getElementById("mySuv-2").style.display = "inline-block";
  document.getElementById("mySuv-3").style.display = "inline-block";
  document.getElementById("mySuv-4").style.display = "inline-block";
  document.getElementById("mySuv-5").style.display = "inline-block";
  document.getElementById("mySuv-6").style.display = "inline-block";
  document.getElementById("mySedan").style.display = "none";
  document.getElementById("myHatchback-1").style.display = "none";
  document.getElementById("myHatchback-2").style.display = "none";
  document.getElementById("myContainer").style.height = "fit-content";
  document.getElementById("noContent").style.display = "none";
    document.getElementById("filterContainer").style.borderBottomRightRadius = "10px";
}
function eightFunction() {
  document.getElementById("sportOne").style.display = "none";
  document.getElementById("sportTwo").style.display = "none";
  document.getElementById("mySuv-1").style.display = "none";
  document.getElementById("mySuv-2").style.display = "none";
  document.getElementById("mySuv-3").style.display = "none";
  document.getElementById("mySuv-4").style.display = "none";
  document.getElementById("mySuv-5").style.display = "none";
  document.getElementById("mySuv-6").style.display = "none";
  document.getElementById("mySedan").style.display = "none";
  document.getElementById("myHatchback-1").style.display = "none";
  document.getElementById("myHatchback-2").style.display = "none";
  document.getElementById("myContainer").style.height = "fit-content";
  document.getElementById("noContent").style.display = "grid";
    document.getElementById("filterContainer").style.borderBottomRightRadius = "10px";
}
